"""Exercise actual local speech, semantic, review, cache, and comparison paths.

Uses only the fictional dialogue generated by generate-highlight-speech-smoke.ps1.
Author: Neil Mitchell
"""

from __future__ import annotations

import argparse
import hashlib
import json
import time
from pathlib import Path
from typing import Any
from unittest.mock import patch

from raid_editor.config.models import HighlightIntelligenceConfig, ProjectConfig
from raid_editor.util.paths import atomic_write_json, quick_file_fingerprint
from raid_editor.workflow import analyse_highlights_project, prepare_highlight_comparison

ROOT = Path(__file__).resolve().parents[1]


def argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=HighlightIntelligenceConfig().model)
    parser.add_argument(
        "--fixture-dir",
        type=Path,
        default=ROOT / "samples" / "generated" / "highlight-intelligence",
        help="Fictional media and fixture-timing.json from generate-highlight-speech-smoke.ps1",
    )
    parser.add_argument(
        "--runtime-root",
        type=Path,
        default=ROOT,
        help="Directory containing explicitly installed .tools and .models (no downloads here)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "reports" / "highlight-intelligence-smoke",
        help="Directory for synthetic workflow artifacts and runtime-smoke.json",
    )
    return parser


def _validate_fixture(source: Path) -> None:
    """Bind fixed timing assertions to the exact authored, generated fixture."""
    manifest = source.with_name("fixture-timing.json")
    if not source.is_file() or not manifest.is_file():
        raise ValueError(
            "Generate the fixed-voice fictional fixture first: "
            "powershell -File scripts/generate-highlight-speech-smoke.ps1"
        )
    timing = json.loads(manifest.read_text(encoding="utf-8-sig"))
    if not isinstance(timing, dict):
        raise ValueError("Invalid fictional fixture timing metadata; regenerate the fixture.")
    with source.open("rb") as handle:
        digest = hashlib.file_digest(handle, "sha256").hexdigest()
    if (
        timing.get("source_sha256") != digest
        or timing.get("voice") != "Microsoft David Desktop - English (United States)"
        or timing.get("speech_rate") != 0
        or timing.get("expected_first_setup_seconds") != 8.21
        or timing.get("expected_final_payoff_seconds") != 40.69
        or timing.get("tolerance_seconds") != 0.2
    ):
        raise ValueError("Fictional fixture timing metadata changed; regenerate the fixture.")


def main(argv: list[str] | None = None) -> None:
    parser = argument_parser()
    arguments = parser.parse_args(argv)
    source = arguments.fixture_dir.expanduser().resolve() / "synthetic-dialogue.mkv"
    try:
        _validate_fixture(source)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    runtime_root = arguments.runtime_root.expanduser().resolve()
    for asset in (
        runtime_root / ".models" / "faster-whisper-medium.en" / "model.bin",
        runtime_root / ".tools" / "ollama-0.33.3" / "ollama.exe",
    ):
        if not asset.is_file():
            parser.error(
                "Install the optional local assets with scripts/setup-highlight-intelligence.py "
                "first, or pass --runtime-root for an existing installation."
            )
    output_dir = arguments.output_dir.expanduser().resolve()
    before = quick_file_fingerprint(source)
    manual = output_dir / "empty-pulls.json"
    atomic_write_json(
        manual,
        {
            "author": "Neil Mitchell",
            "last_modified_by": "Neil Mitchell",
            "pulls": [],
        },
    )
    config = ProjectConfig.model_validate(
        {
            "project": {"name": "Synthetic Highlight Intelligence Smoke", "game": "Test fixture"},
            "input": {"recording": source, "manual_pulls": manual},
            "audio": {
                "game_track": 1,
                "discord_track": 2,
                "microphone_track": 3,
                "keep_game_audio": True,
                "keep_discord_audio": False,
                "remove_microphone": True,
            },
            "music": {"library": ROOT / "music" / "music-library.json"},
            "highlights": {
                "keep_microphone_audio": True,
                "intelligence": {
                    "enabled": True,
                    "required": True,
                    "model": arguments.model,
                    "whisper_model_path": runtime_root / ".models" / "faster-whisper-medium.en",
                    "ollama_executable": runtime_root / ".tools" / "ollama-0.33.3" / "ollama.exe",
                    "ollama_models_path": runtime_root / ".models" / "ollama",
                    "visual_verification": False,
                },
            },
            "preview": {"review_media_format": "webm"},
        }
    )
    with patch("raid_editor.workflow.project_output_dir", return_value=output_dir / "workflow"):
        _exercise(config, source, before, output_dir)


def _exercise(
    config: ProjectConfig,
    source: Path,
    before: dict[str, Any],
    output_dir: Path,
) -> None:
    started = time.monotonic()
    candidates, paths = analyse_highlights_project(config, create_review_media=True)
    elapsed = time.monotonic() - started
    status = json.loads((paths.highlights / "intelligence-status.json").read_text(encoding="utf-8"))
    if status["status"] != "complete":
        raise RuntimeError(f"Synthetic local analysis did not complete: {status['status']}")
    complete_moments = [
        row
        for row in candidates
        if row.origin == "semantic"
        and row.setup_seconds is not None
        and row.setup_seconds <= 8.41
        and row.payoff_seconds is not None
        and row.payoff_seconds >= 40.49
        and row.start_seconds <= 8.21
        and row.end_seconds >= 40.69
    ]
    if not complete_moments:
        raise RuntimeError(
            "Synthetic shortcut joke must include its first setup and final graveyard payoff"
        )
    if any(row.include for row in candidates):
        raise RuntimeError("Analysis unexpectedly approved a highlight")
    cached_started = time.monotonic()
    repeated, _ = analyse_highlights_project(config, create_review_media=False)
    cached_elapsed = time.monotonic() - cached_started
    if repeated != candidates:
        raise RuntimeError("Cached recommendations changed without changed evidence")
    page = prepare_highlight_comparison(config)
    if quick_file_fingerprint(source) != before:
        raise RuntimeError("Synthetic input was modified by the workflow")
    report = {
        "schema_version": 1,
        "author": "Neil Mitchell",
        "last_modified_by": "Neil Mitchell",
        "fixture": "Fictional synthetic TTS; not real raid quality validation",
        "status": "passed",
        "coverage": status["status"],
        "models": status["models"],
        "analysis_and_review_seconds": elapsed,
        "cached_analysis_seconds": cached_elapsed,
        "candidates": [candidate.model_dump(mode="json") for candidate in candidates],
        "comparison_page": str(page),
        "source_unchanged": True,
        "approvals_created": 0,
        "transcript_persisted": False,
        "fictional_boundary_check": {
            "expected_first_setup_seconds": 8.21,
            "expected_final_payoff_seconds": 40.69,
            "tolerance_seconds": 0.2,
            "complete_moment_candidates": len(complete_moments),
        },
    }
    destination = output_dir / "runtime-smoke.json"
    atomic_write_json(destination, report)
    print(
        json.dumps(
            {
                "status": "passed",
                "candidates": len(candidates),
                "elapsed_seconds": round(elapsed, 2),
                "cached_seconds": round(cached_elapsed, 2),
                "report": str(destination),
                "comparison": str(page),
            }
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
